### ISSUE TITLE
authManagement:verifySignup - Method: create: users.find is not a function

### ISSUE THREAD

**Issue by foxhound87** [feathers-plus/feathers-authentication-management#74]
1. The feathers app was initially created used the cli generator.
2. The auth manager is initialized after all other services.
3. After the user is created, the verify email is sent. 
4. Clicking the link, the client app calls `verifySignupLong(token)`.
5. Then on the server, the auth manager `verifySignupWithLongToken` function is called, which should call the users service, but the I get this error:

```javascript
authManagement:main service called. action=verifySignupLong +35s
  authManagement:verifySignup verifySignup { verifyToken: 'c18b98c317d6bd5ca99b92a338dc0c' } { verifyToken: 'c18b98c317d6bd5ca99b92a338dc0c' } +54s
info: error: authManagement - Method: create: users.find is not a function
error:  TypeError: users.find is not a function
    at verifySignup (/app/node_modules/feathers-authentication-management/lib/verifySignup.js:38:16)
    at /app/node_modules/feathers-authentication-management/lib/verifySignup.js:18:12
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The strange thing is that only if I restart the server the call is done without errors and it recognize the users service.

For now I had to make a workaround:

I cloned this repo and passed the users service in the main auth manager function.

```javascript
  app.configure(authManagement({
    users: app.service('users'),
    notifier,
  }));
``` 

then I changed all repo users service calls to this:

```javascript
  // const users = options.app.service(options.service);
  const users = options.users;
```

It worked well, but I want to understand what's wrong here, I don't have time to recreate the whole app from ground zero as this has already took me much time and really want to use this package without workarounds. 

Lastly, why the context of `this` feathers app is also wrong tough the auth manager is configured after all other services?

Thanks

```
    "feathers": "^2.2.0",
    "feathers-authentication": "^1.2.7",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
    "feathers-authentication-management": "^1.0.0",
    "feathers-authentication-oauth2": "^0.2.5",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.9.2",
    "feathers-hooks": "^2.0.2",
    "feathers-hooks-common": "^3.7.2",
    "feathers-mongoose": "^5.1.2",
    "feathers-rest": "^1.8.0",
    "feathers-socketio": "^2.0.0",
```

**Comment by foxhound87** [comment]
https://gist.github.com/foxhound87/a9e958250aeda0113fd43836c5599e0a

This gist is my app configuration tested with only the users service imported in `/services/index.js` and all users services hooks disabled (except the needed ones).

**Comment by foxhound87** [comment]
Now I'm creating an new app by everything not needed (and the workaround too).
Surprisingly the `verifySignupLong` doesn't work at all.
I'm getting this timeout error when calling it from the client:

```
Timeout of 5000ms exceeded calling authManagement::create

Error: Timeout of 5000ms exceeded calling authManagement::create
    at Timeout._onTimeout (/app/node_modules/feathers-socket-commons/lib/client.js:87:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

all others actions are still working as in the previous app.
I will create a repo asap.

**Comment by slightlytrue** [comment]
@foxhound87 I'm getting the error on `verifySignupLong`  when using sequelize and mariadb.

```js
const app = feathers()
  .configure(feathers.hooks())
  .configure(feathers.rest('http://localhost:3030').axios(window.axios));

// ... vue component method
function verifySignup(verifyToken) {
      if(!verifyToken) { return false; }
      
      const authManagement = app.service('authManagement');
     
      // below one also did not worked
      // fetch('/authManagement', {
      //   method: 'POST', headers: { Accept: 'application/json' },
      //   body: JSON.stringify({ action: 'verifySignupLong', value: verifyToken})
      // }).then(res => res.json())

      authManagement.create({
        action: 'verifySignupLong',
        value: verifyToken
      })
        .then(result => {
          this.verified = true;
          this.message = 'Your email has been verified. Please log in to app!';
          this.showAlert = true;
          log('Success ', result);
        })
        .catch(err => {
          this.message = 'Sorry, but we could not verify your email.';
          this.verified = false;
          this.showAlert = true;
          log('Error ',err);
        });
}
```

The error i get  on server: 

```bash
info: after: users - Method: find
info: error: users - Method: patch: Invalid value [object Object]
error:  Error: Invalid value [object Object]
    at Object.escape (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\sql-string.js:50:11)
    at Object.escape (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:919:22)
    at Object.updateQuery (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:360:58)
    at QueryInterface.bulkUpdate (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\query-interface.js:944:37)
    at Promise.try.then.then.then.results (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\model.js:2760:34)
    at tryCatcher (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
info: error: authManagement - Method: create: Invalid value [object Object]
error:  Error: Invalid value [object Object]
    at Object.escape (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\sql-string.js:50:11)
    at Object.escape (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:919:22)
    at Object.updateQuery (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\dialects\abstract\query-generator.js:360:58)
    at QueryInterface.bulkUpdate (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\query-interface.js:944:37)
    at Promise.try.then.then.then.results (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\sequelize\lib\model.js:2760:34)
    at tryCatcher (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Harry\Documents\code\apps\electron-apps\potential-waffle-chat-server\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

```

**Comment by eddyystop** [comment]
@slightlytrue I believe this addresses your issue https://github.com/feathers-plus/feathers-authentication-management/issues/44

**Comment by foxhound87** [comment]
I created the repo with the issue: 
https://bitbucket.org/foxhound87/feathers-auth-manager-issue-74

Please take a look, in the meantime I'm trying to update to the new feathers version and I will check if the issue persists.

**Comment by eddyystop** [comment]
I will look into this when I return from vacation next Wednesday.

**Comment by foxhound87** [comment]
@eddyystop it seems is working correctly with feathers buzzard, I will do more tests in the next days.

**Comment by foxhound87** [comment]
`passwordChange` is working in a strange way (it changes the password, but no response from server is returned), instead I get timeout on client:

`Timeout of 5000ms exceeded calling create on authManagement`

Server Prints No Log, instead this is shown:
```
Publishing all events to all authenticated users. See `channels.js` and https://docs.feathersjs.com/api/channels.html for more information.
Publishing all events to all authenticated users. See `channels.js` and https://docs.feathersjs.com/api/channels.html for more information.
```

**Comment by foxhound87** [comment]
Also when I get `error:  BadRequest: Current password is incorrect.` on the server, the error is not sent to the client.

**Comment by eddyystop** [comment]
I'm on vacation till Jan 10. I can look into these items when I return. I might need @marshallswain  's input.

**Comment by eddyystop** [comment]
The options default to `{ service: '/users' }` https://github.com/feathers-plus/feathers-authentication-management/blob/master/src/service.js#L19

And the repo uses `app.service(options.service)` to get a handle to the user service https://github.com/feathers-plus/feathers-authentication-management/blob/master/src/passwordChange.js#L17

Your `{ users: app.service('users') }` and `it seems is working correctly with feathers buzzard,` both suggest that either options.service was set wrong, or somehow the Feathers services were not initialized yet (happens in `app.listen(...)`) when the service was called.

**Comment by eddyystop** [comment]
I don't have MariahDB so I can't run your repo. 

`info: error: users - Method: patch: Invalid value [object Object]` suggests that you are not using a JSON column as is required with SQL DBs. This is why I referred you to https://github.com/feathers-plus/feathers-authentication-management/issues/44

Please indicate it you followed the advice given there.

**Comment by eddyystop** [comment]
I think you need to handle these issues one at a time. Your subsequent observations may be just a cascade from these ones.

**Comment by foxhound87** [comment]
@eddyystop I'm using mongodb not mariadb (@slightlytrue was using mariadb). 

I think I solved it on buzzard (removing `authenticate('jwt')` and without using `{ users: app.service('users') }` with the latest version of the package with the default options), but I don't want to have security issues, so I need to be sure about removing `authenticate('jwt')` and I also want to understand what's wrong in my repo with feathers auk. Thank You.

**Comment by foxhound87** [comment]
When I try to call the forgot password, I'm still getting the error `users.find is not a function` with the version 1 of the package, and I noticed that I get this only in the production environment.

and after updating the package to the version 2 I get a different error:

```
 / path: authManagement / type: error / method: create / id: undefined
{ query: {}, route: {}, provider: 'socketio' }
error:  BadRequest: User not found.
    at new BadRequest (/app/node_modules/feathers-authentication-management/node_modules/@feathersjs/errors/lib/index.js:86:17)
    at getUserData (/app/node_modules/feathers-authentication-management/lib/helpers.js:93:11)
    at /app/node_modules/feathers-authentication-management/lib/sendResetPwd.js:32:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by eddyystop** [comment]
The repo has no sense of a dev or prod env. So I suggest you look at what's different in your config or set of files for the two modes.

**Comment by foxhound87** [comment]
I updated to the version 2.0 with feathers buzzard, same configuration, and it works

**Comment by eddyystop** [comment]
Good to hear that!

**Comment by foxhound87** [comment]
I have to reopen this issue because I still getting **occasionally** the error, just after the deploy it works, but after some time the app is running the error comes back (only in production). I have others environment which has no problems, the configs are all ok.

```
error: TypeError: users.find is not a function at /app/node_modules/feathers-authentication-management/lib/resendVerifySignup.js:32:31 at
at process._tickCallback (internal/process/next_tick.js:188:7) at process._tickCallback (internal/process/next_tick.js:188:7) { query: {}, route: {}, provider: 'socketio' } error: TypeError: users.find is not a function at /app/node_modules/feathers-authentication-management/lib/resendVerifySignup.js:32:31
```

**Comment by eddyystop** [comment]
I don't know how I can help because the problem only appears in production and after some time. I suggest you catch the error, find what `users` is at that time, and what statement it fails on.

**Comment by foxhound87** [comment]
I've cloned the repo and logged the options.service in the resendVerifySignup function which in my case is authManagement and not users... this happens only after verifyHooks.addVerification() is called when a new user is created, and if I restart the server all is working.

**Comment by foxhound87** [comment]
I've made a temporary workaround adding `options.service = 'users';` in the last callback of `addVerification`:

```
.then(([options, longToken, shortToken]) => {
      options.service = 'users';
      ...
```

please let me know...

**Comment by foxhound87** [comment]
UP
